spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itcast?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
logging:
  level:
    root: warn
    com.linyuan.blog: info
  file: log/blog-pro.log
server:
  port: 8081

